apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.34.0
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.34.0
  releaseNotes: "kapp-controller 0.34.0 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:1bd4eada322086d189ec6f1505672213f39674a842be30d18d591eefa9f88a4a
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
